#!/usr/bin/env python3
"""
build_web.py  -  inline web/ sources into firmware/walkie_talkie/web_client.h

Reads web/index.html, replaces <link href="style.css"> and
<script src="app.js"> with inline <style>/<script> blocks, then writes
the result as a PROGMEM raw-string literal for the ESP32 to serve.

Usage:
    python tools/build_web.py
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
WEB  = ROOT / "web"
OUT  = ROOT / "firmware" / "walkie_talkie" / "web_client.h"


def main() -> int:
    try:
        html = (WEB / "index.html").read_text(encoding="utf-8")
        css  = (WEB / "style.css").read_text(encoding="utf-8")
        js   = (WEB / "app.js").read_text(encoding="utf-8")
    except FileNotFoundError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    html = re.sub(
        r'<link\s[^>]*href=["\']style\.css["\'][^>]*>',
        "<style>\n" + css + "</style>",
        html,
        count=1,
    )
    html = re.sub(
        r'<script\s[^>]*src=["\']app\.js["\'][^>]*></script>',
        "<script>\n" + js + "</script>",
        html,
        count=1,
    )

    # Guard against unlikely raw-string delimiter collision
    if ')HTML"' in html:
        print(
            "error: embedded content contains the raw-string delimiter ')HTML\"'; "
            "pick a different delimiter in this script",
            file=sys.stderr,
        )
        return 2

    header = (
        "// ============================================================\n"
        "//  AUTO-GENERATED by tools/build_web.py  -  DO NOT EDIT BY HAND\n"
        "//  Edit web/index.html, web/style.css, web/app.js and rerun:\n"
        "//      python tools/build_web.py\n"
        "// ============================================================\n"
        "#pragma once\n"
        "\n"
        "static const char INDEX_HTML[] PROGMEM = R\"HTML(\n"
        + html
        + "\n)HTML\";\n"
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header, encoding="utf-8")
    print(f"wrote {OUT}  ({len(header):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
